import {Country} from './country';

export const COUNTRIES: Country[]  = [
    {
        name: 'United States',
        capital: 'Washington, D.C.',
        largest_city: 'New York City',
        area: '9833520',
        population: '331449281',
        GDP: '22940000',
        currency: 'U.S. dollar($) (USD)',
      },
      {
        name: 'China',
        capital: 'Beijing',
        largest_city: 'Shanghai',
        area: '9596961',
        population: '1411778724',
        GDP: '26660000',
        currency: 'Renminbi(元/¥) (CNY)',
      },
      {
        name: 'Indonesia',
        capital: 'Jakarta',
        largest_city: 'Jakarta',
        area: '1904569',
        population: '270203917',
        GDP: '3507000',
        currency: 'Indonesian rupiah (Rp) (IDR)',
      },
      {
        name: 'Japan',
        capital: 'Tokyo',
        largest_city: 'Tokyo',
        area: '377975',
        population: '125360000',
        GDP: '5586000',
        currency: 'Japanese yen (¥)',
      },
      {
        name: 'South Korea',
        capital: 'Seoul',
        largest_city: 'Seoul',
        area: '100363',
        population: '51709098',
        GDP: '2436000',
        currency: 'Korean Republic won (₩) (KRW)',
      },
      {
        name: 'Malaysia',
        capital: 'Kuala Lumpur',
        largest_city: 'Kuala Lumpur',
        area: '330803',
        population: '32730000',
        GDP: '900426',
        currency: 'Ringgit (RM) (MYR)',
      },
      {
        name: 'Denmark',
        capital: 'Copenhagen',
        largest_city: 'Copenhagen',
        area: '2220930',
        population: '5850189',
        GDP: '299',
        currency: 'Danish krone (DKK)',
      }
]